# Generated by Django 5.2.4 on 2025-07-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_author_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='content',
        ),
    ]
