# Generated by Django 5.2.4 on 2025-08-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_listitems_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitems',
            old_name='section',
            new_name='blog',
        ),
    ]
