# Generated by Django 5.2.4 on 2025-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogsection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
