# Generated by Django 5.2.4 on 2025-08-04 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_section_listitems_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='blog.blogsection'),
        ),
    ]
