# Generated by Django 5.2.4 on 2025-08-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_listitems_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
