# Generated by Django 5.2.4 on 2025-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogsection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
