# Generated by Django 5.2.4 on 2025-08-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_listitems_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitems',
            old_name='title',
            new_name='item',
        ),
    ]
