# Generated by Django 5.2.4 on 2025-08-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_file', models.FileField(upload_to='./downloads')),
            ],
        ),
        migrations.CreateModel(
            name='ModbusSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_file', models.FileField(upload_to='./downloads')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='./downloads'),
        ),
        migrations.AddField(
            model_name='product',
            name='calibration_software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.calibrationsoftware'),
        ),
        migrations.AddField(
            model_name='product',
            name='modbus_software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.modbussoftware'),
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
