# Generated by Django 5.2.4 on 2025-08-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_calibrationsoftware_modbussoftware_product_datasheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsoftware',
            name='software_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsoftware',
            name='software_version',
            field=models.CharField(default='latest', max_length=255),
        ),
        migrations.AddField(
            model_name='modbussoftware',
            name='software_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modbussoftware',
            name='software_version',
            field=models.CharField(default='latest', max_length=255),
        ),
    ]
