# Generated by Django 5.2.4 on 2025-08-17 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_calibrationsoftware_software_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calibration_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.calibrationsoftware'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modbus_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.modbussoftware'),
        ),
    ]
